//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen2_LMP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        public int matricula_alumno { get; set; }
        public string nombre_alumno { get; set; }
        public string apellido_paterno_alumno { get; set; }
        public string apellido_materno_alumno { get; set; }
        public string direccion_alumno { get; set; }
        public string telefono_alumno { get; set; }
        public string correo_alumno { get; set; }
        public string carrera { get; set; }
        public int semestre_alumno { get; set; }
    }
}
