//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Examen2_LMP.DataAccess
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class LMPEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new LMPEntities object using the connection string found in the 'LMPEntities' section of the application configuration file.
        /// </summary>
        public LMPEntities() : base("name=LMPEntities", "LMPEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LMPEntities object.
        /// </summary>
        public LMPEntities(string connectionString) : base(connectionString, "LMPEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LMPEntities object.
        /// </summary>
        public LMPEntities(EntityConnection connection) : base(connection, "LMPEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Alumno> Alumno
        {
            get
            {
                if ((_Alumno == null))
                {
                    _Alumno = base.CreateObjectSet<Alumno>("Alumno");
                }
                return _Alumno;
            }
        }
        private ObjectSet<Alumno> _Alumno;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Alumno EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAlumno(Alumno alumno)
        {
            base.AddObject("Alumno", alumno);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LMPModel", Name="Alumno")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Alumno : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Alumno object.
        /// </summary>
        /// <param name="matricula_alumno">Initial value of the matricula_alumno property.</param>
        /// <param name="nombre_alumno">Initial value of the nombre_alumno property.</param>
        /// <param name="apellido_paterno_alumno">Initial value of the apellido_paterno_alumno property.</param>
        /// <param name="apellido_materno_alumno">Initial value of the apellido_materno_alumno property.</param>
        /// <param name="direccion_alumno">Initial value of the direccion_alumno property.</param>
        /// <param name="telefono_alumno">Initial value of the telefono_alumno property.</param>
        /// <param name="correo_alumno">Initial value of the correo_alumno property.</param>
        /// <param name="carrera">Initial value of the carrera property.</param>
        /// <param name="semestre_alumno">Initial value of the semestre_alumno property.</param>
        public static Alumno CreateAlumno(global::System.Int32 matricula_alumno, global::System.String nombre_alumno, global::System.String apellido_paterno_alumno, global::System.String apellido_materno_alumno, global::System.String direccion_alumno, global::System.String telefono_alumno, global::System.String correo_alumno, global::System.String carrera, global::System.Int32 semestre_alumno)
        {
            Alumno alumno = new Alumno();
            alumno.matricula_alumno = matricula_alumno;
            alumno.nombre_alumno = nombre_alumno;
            alumno.apellido_paterno_alumno = apellido_paterno_alumno;
            alumno.apellido_materno_alumno = apellido_materno_alumno;
            alumno.direccion_alumno = direccion_alumno;
            alumno.telefono_alumno = telefono_alumno;
            alumno.correo_alumno = correo_alumno;
            alumno.carrera = carrera;
            alumno.semestre_alumno = semestre_alumno;
            return alumno;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 matricula_alumno
        {
            get
            {
                return _matricula_alumno;
            }
            set
            {
                if (_matricula_alumno != value)
                {
                    Onmatricula_alumnoChanging(value);
                    ReportPropertyChanging("matricula_alumno");
                    _matricula_alumno = StructuralObject.SetValidValue(value, "matricula_alumno");
                    ReportPropertyChanged("matricula_alumno");
                    Onmatricula_alumnoChanged();
                }
            }
        }
        private global::System.Int32 _matricula_alumno;
        partial void Onmatricula_alumnoChanging(global::System.Int32 value);
        partial void Onmatricula_alumnoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre_alumno
        {
            get
            {
                return _nombre_alumno;
            }
            set
            {
                Onnombre_alumnoChanging(value);
                ReportPropertyChanging("nombre_alumno");
                _nombre_alumno = StructuralObject.SetValidValue(value, false, "nombre_alumno");
                ReportPropertyChanged("nombre_alumno");
                Onnombre_alumnoChanged();
            }
        }
        private global::System.String _nombre_alumno;
        partial void Onnombre_alumnoChanging(global::System.String value);
        partial void Onnombre_alumnoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String apellido_paterno_alumno
        {
            get
            {
                return _apellido_paterno_alumno;
            }
            set
            {
                Onapellido_paterno_alumnoChanging(value);
                ReportPropertyChanging("apellido_paterno_alumno");
                _apellido_paterno_alumno = StructuralObject.SetValidValue(value, false, "apellido_paterno_alumno");
                ReportPropertyChanged("apellido_paterno_alumno");
                Onapellido_paterno_alumnoChanged();
            }
        }
        private global::System.String _apellido_paterno_alumno;
        partial void Onapellido_paterno_alumnoChanging(global::System.String value);
        partial void Onapellido_paterno_alumnoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String apellido_materno_alumno
        {
            get
            {
                return _apellido_materno_alumno;
            }
            set
            {
                Onapellido_materno_alumnoChanging(value);
                ReportPropertyChanging("apellido_materno_alumno");
                _apellido_materno_alumno = StructuralObject.SetValidValue(value, false, "apellido_materno_alumno");
                ReportPropertyChanged("apellido_materno_alumno");
                Onapellido_materno_alumnoChanged();
            }
        }
        private global::System.String _apellido_materno_alumno;
        partial void Onapellido_materno_alumnoChanging(global::System.String value);
        partial void Onapellido_materno_alumnoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String direccion_alumno
        {
            get
            {
                return _direccion_alumno;
            }
            set
            {
                Ondireccion_alumnoChanging(value);
                ReportPropertyChanging("direccion_alumno");
                _direccion_alumno = StructuralObject.SetValidValue(value, false, "direccion_alumno");
                ReportPropertyChanged("direccion_alumno");
                Ondireccion_alumnoChanged();
            }
        }
        private global::System.String _direccion_alumno;
        partial void Ondireccion_alumnoChanging(global::System.String value);
        partial void Ondireccion_alumnoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String telefono_alumno
        {
            get
            {
                return _telefono_alumno;
            }
            set
            {
                Ontelefono_alumnoChanging(value);
                ReportPropertyChanging("telefono_alumno");
                _telefono_alumno = StructuralObject.SetValidValue(value, false, "telefono_alumno");
                ReportPropertyChanged("telefono_alumno");
                Ontelefono_alumnoChanged();
            }
        }
        private global::System.String _telefono_alumno;
        partial void Ontelefono_alumnoChanging(global::System.String value);
        partial void Ontelefono_alumnoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String correo_alumno
        {
            get
            {
                return _correo_alumno;
            }
            set
            {
                Oncorreo_alumnoChanging(value);
                ReportPropertyChanging("correo_alumno");
                _correo_alumno = StructuralObject.SetValidValue(value, false, "correo_alumno");
                ReportPropertyChanged("correo_alumno");
                Oncorreo_alumnoChanged();
            }
        }
        private global::System.String _correo_alumno;
        partial void Oncorreo_alumnoChanging(global::System.String value);
        partial void Oncorreo_alumnoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String carrera
        {
            get
            {
                return _carrera;
            }
            set
            {
                OncarreraChanging(value);
                ReportPropertyChanging("carrera");
                _carrera = StructuralObject.SetValidValue(value, false, "carrera");
                ReportPropertyChanged("carrera");
                OncarreraChanged();
            }
        }
        private global::System.String _carrera;
        partial void OncarreraChanging(global::System.String value);
        partial void OncarreraChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 semestre_alumno
        {
            get
            {
                return _semestre_alumno;
            }
            set
            {
                Onsemestre_alumnoChanging(value);
                ReportPropertyChanging("semestre_alumno");
                _semestre_alumno = StructuralObject.SetValidValue(value, "semestre_alumno");
                ReportPropertyChanged("semestre_alumno");
                Onsemestre_alumnoChanged();
            }
        }
        private global::System.Int32 _semestre_alumno;
        partial void Onsemestre_alumnoChanging(global::System.Int32 value);
        partial void Onsemestre_alumnoChanged();

        #endregion

    }

    #endregion

}
